### ISSUE TITLE
with version 1.1.0 I get ModuleNotFoundError: No module named 'transformers' 

### ISSUE THREAD

**Issue by lfoppiano** [nlp-uoregon/trankit#37]
Hi, 
   I just have a fresh installation (version 1.1.0) and when running it (I'm testing the sentence segmentation) I get the following error: 

```
[...]
    from trankit import Pipeline
  File "/home/Luca/.conda/envs/ss/lib/python3.7/site-packages/trankit/__init__.py", line 1, in <module>
    from .pipeline import Pipeline
  File "/home/Luca/.conda/envs/ss/lib/python3.7/site-packages/trankit/pipeline.py", line 2, in <module>
    from .models.base_models import Multilingual_Embedding
  File "/home/Luca/.conda/envs/ss/lib/python3.7/site-packages/trankit/models/__init__.py", line 1, in <module>
    from .classifiers import *
  File "/home/Luca/.conda/envs/ss/lib/python3.7/site-packages/trankit/models/classifiers.py", line 2, in <module>
    from .base_models import *
  File "/home/Luca/.conda/envs/ss/lib/python3.7/site-packages/trankit/models/base_models.py", line 1, in <module>
    from ..adapter_transformers import AdapterType, XLMRobertaModel
  File "/home/Luca/.conda/envs/ss/lib/python3.7/site-packages/trankit/adapter_transformers/__init__.py", line 562, in <module>
    from .modeling_tf_electra import (
  File "/home/Luca/.conda/envs/ss/lib/python3.7/site-packages/trankit/adapter_transformers/modeling_tf_electra.py", line 5, in <module>
    from transformers import ElectraConfig
ModuleNotFoundError: No module named 'transformers'
```

these are the libraries that I have installed: 

```
Package                Version
---------------------- -------------------
absl-py                0.13.0
astunparse             1.6.3
blingfire              0.1.3
blis                   0.7.4
cachetools             4.2.2
catalogue              1.0.0
certifi                2021.5.30
chardet                4.0.0
click                  8.0.1
cymem                  2.0.5
de-core-news-lg        2.3.0
de-core-news-sm        2.3.0
deepsegment            2.3.1
en-core-sci-lg         0.3.0
en-core-sci-sm         0.3.0
en-core-web-lg         2.3.1
en-core-web-sm         2.3.1
filelock               3.3.1
fr-core-news-lg        2.3.0
fr-core-news-sm        2.3.0
gast                   0.3.3
gensim                 3.8.3
google-auth            1.32.0
google-auth-oauthlib   0.4.4
google-pasta           0.2.0
grpcio                 1.38.1
h5py                   2.10.0
idna                   2.10
importlib-metadata     4.5.0
joblib                 1.0.1
JPype1                 1.3.0
Keras                  2.3.1
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.2
langid                 1.1.6
Markdown               3.3.4
murmurhash             1.0.5
nltk                   3.5
nnsplit                0.5.7.post0
numpy                  1.21.0
oauthlib               3.1.1
onnxruntime            1.7.0
opt-einsum             3.3.0
packaging              21.0
pip                    21.1.2
plac                   1.1.3
preshed                3.0.5
progressbar2           3.53.1
protobuf               3.17.3
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pydload                1.0.9
pyparsing              3.0.3
pysbd                  0.3.3
python-utils           2.5.6
PyYAML                 5.4.1
regex                  2021.8.28
requests               2.25.1
requests-oauthlib      1.3.0
rsa                    4.7.2
sacremoses             0.0.46
scikit-learn           0.24.2
scipy                  1.4.1
sentence-splitter      1.4
sentencepiece          0.1.96
seqeval                0.0.3
seqtag-keras           1.0.6
setuptools             52.0.0.post20210125
six                    1.16.0
smart-open             5.1.0
spacy                  2.3.4
srsly                  1.0.5
stanza                 1.1.1
syntok                 1.3.1
tensorboard            2.2.2
tensorboard-plugin-wit 1.8.0
tensorflow             2.2.0
tensorflow-estimator   2.2.0
termcolor              1.1.0
thinc                  7.4.5
threadpoolctl          2.1.0
tokenizers             0.10.3
torch                  1.7.1
tqdm                   4.61.1
trankit                1.1.0
typing-extensions      3.10.0.0
urllib3                1.26.5
wasabi                 0.8.2
Werkzeug               2.0.1
wheel                  0.36.2
wrapt                  1.12.1
zipp                   3.4.1
```

I installed `transformers` manually (#32) but it didn't seems to help: 

```
Traceback (most recent call last):
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/transformers/file_utils.py", line 2150, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/transformers/modeling_tf_utils.py", line 30, in <module>
    from tensorflow.python.keras.engine.keras_tensor import KerasTensor
ModuleNotFoundError: No module named 'tensorflow.python.keras.engine.keras_tensor'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/transformers/file_utils.py", line 2150, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/transformers/models/__init__.py", line 19, in <module>
    from . import (
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/transformers/models/layoutlm/__init__.py", line 22, in <module>
    from .configuration_layoutlm import LAYOUTLM_PRETRAINED_CONFIG_ARCHIVE_MAP, LayoutLMConfig
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/transformers/models/layoutlm/configuration_layoutlm.py", line 22, in <module>
    from ...onnx import OnnxConfig, PatchingSpec
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/transformers/onnx/__init__.py", line 17, in <module>
    from .convert import export, validate_model_outputs
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/transformers/onnx/convert.py", line 23, in <module>
    from .. import PreTrainedModel, PreTrainedTokenizer, TensorType, TFPreTrainedModel, is_torch_available
  File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/transformers/file_utils.py", line 2140, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/transformers/file_utils.py", line 2154, in _get_module
    ) from e
RuntimeError: Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
No module named 'tensorflow.python.keras.engine.keras_tensor'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "segmentation_study/metrics.py", line 6, in <module>
    from segmenters import *
  File "/Users/lfoppiano/development/projects/sentence-segmentation/sentence-segmentation/segmentation_study/segmenters.py", line 10, in <module>
    from trankit import Pipeline
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/trankit/__init__.py", line 1, in <module>
    from .pipeline import Pipeline
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/trankit/pipeline.py", line 2, in <module>
    from .models.base_models import Multilingual_Embedding
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/trankit/models/__init__.py", line 1, in <module>
    from .classifiers import *
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/trankit/models/classifiers.py", line 2, in <module>
    from .base_models import *
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/trankit/models/base_models.py", line 1, in <module>
    from ..adapter_transformers import AdapterType, XLMRobertaModel
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/trankit/adapter_transformers/__init__.py", line 562, in <module>
    from .modeling_tf_electra import (
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/trankit/adapter_transformers/modeling_tf_electra.py", line 5, in <module>
    from transformers import ElectraConfig
  File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/transformers/file_utils.py", line 2140, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/Users/lfoppiano/opt/anaconda3/envs/ss/lib/python3.7/site-packages/transformers/file_utils.py", line 2154, in _get_module
    ) from e
RuntimeError: Failed to import transformers.models.electra because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
No module named 'tensorflow.python.keras.engine.keras_tensor'
```

**Update:** 

After I uninstall `transformers` and installed `adapter-transfomers` it seems to work fine...

**Comment by mrgransky** [comment]
did u do: `pip install transformers trankit` to get rid of the error?

**Comment by lfoppiano** [comment]
> After I uninstall transformers and installed adapter-transfomers it seems to work fine...

**Comment by minhhdvn** [comment]
Thanks for reporting the issue.
It seems that the error was fixed. 
So we closed the issue.
